on:
  push:
    branches:
      - main
permissions:
  contents:
    write
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove current build
        run: |
          rm build/decisco.crx
          rm build/decisco.zip
      
      - name: Pack extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'src'
          zipFilePath: 'build/decisco.zip'
      
      - name: Generate CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/decisco.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Commit
        run: |
          git config --global user.name 'stevex86'
          git config --global user.email 'stevex86@users.noreply.github.com'
          git add ./build
          git commit -am "Generated CRX"
          git push
