on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # pack zip and read manifest, can be reused in the following steps
      - name: Pack extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'src'
          zipFilePath: 'build/extension.zip'
      
      - name: Generate CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/decisco.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Commit
        run: |
          git config --global user.name 'stevex86'
          git config --global user.email 'stevex86@users.noreply.github.com'
          git add ./build
          git commit -am "Generated CRX"
          git push
